export const SORT_OPTIONS = {
  CASE_START: "Case Start",
  CONTRACT: "Contract",
  MORTGAGE_TITLE: "Mortgage & Title",
  CLOSING: "Closing",
};
export const casesCardData = [
  {
    title: "Setting Up",
    count: 11,
    items: [
      {
        badgeColor: "yellow",
        badgeText: "Not Started",
        caseDetails: "535 W 52nd St #9G coop",

        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Not Started",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Not Started",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "green",
        badgeText: "All Done",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "green",
        badgeText: "All Done",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "green",
        badgeText: "All Done",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
    ],
  },
  {
    title: "Contract Preparing",
    count: 11,
    items: [
      {
        badgeColor: "yellow",
        badgeText: "Unfinished",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Unfinished",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Unfinished",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "gray",
        badgeText: "Waiting",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "gray",
        badgeText: "Waiting",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "gray",
        badgeText: "Waiting",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "gray",
        badgeText: "Waiting",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
    ],
  },
  {
    title: "Contract Signing",
    count: 11,
    items: [
      {
        badgeColor: "red",
        badgeText: "No Response",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "red",
        badgeText: "No Response",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Unfinished",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Not Started",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Not Started",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Not Started",
        caseDetails: "Client’s Name - Location",
      },
      {
        badgeColor: "gray",
        badgeText: "Waiting",
        caseDetails: "Client’s Name - Location",
      },
    ],
  },
  {
    title: "Mortgage & Title",
    count: 11,
    items: [
      {
        badgeColor: "red",
        badgeText: "No Response",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "red",
        badgeText: "No Response",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Not Started",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Not Started",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "green",
        badgeText: "All Done",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "green",
        badgeText: "All Done",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "green",
        badgeText: "All Done",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
    ],
  },
  {
    title: "Closing",
    count: 11,
    items: [
      {
        badgeColor: "yellow",
        badgeText: "Not Started",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "yellow",
        badgeText: "Not Started",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "green",
        badgeText: "All Done",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "gray",
        badgeText: "Waiting",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
      {
        badgeColor: "gray",
        badgeText: "Waiting",
        caseDetails: "535 W 52nd St #9G coop",
        caseTitle: "Gee, First Name",
        caseCount: "1/3",
      },
    ],
  },
];
export const caseDetailTab = {
  PARTICIPANTS: 1,
  PREMISES: 2,
  OTHERS: 3,
};
